/**
 * backfill-historical-odds.ts — Fetches and caches historical odds from The Odds API
 * for all historical backtest snapshots (2023 onward).
 *
 * Cache location: cache/historical-odds/{sport_key}/{YYYY-MM-DD}.json
 * Each file contains the full API response for that sport_key at {date}T00:00:00Z,
 * which includes pre-match odds for all games scheduled that day.
 *
 * Resume-safe: skips dates that already have a cached file.
 *
 * Prerequisite: backtest snapshot files must exist in cache/predictions/ for the league.
 *   Run scripts/run-backtest-v3-historical.ts first if they don't exist.
 *   For AF canonical leagues (CL, AR, BR, MX): run-backtest-v3-historical.ts reads from
 *   cache/historical/apifootball/{leagueId}/{year}.json (generated by calibrate-league-report.ts).
 *
 * This tool is called automatically by the /calibrate-league skill (Step 3.5) after
 * calibration is wired. It can also be run manually at any time — it is resume-safe.
 *
 * Usage:
 *   npx tsx --tsconfig tsconfig.server.json tools/backfill-historical-odds.ts
 *   npx tsx --tsconfig tsconfig.server.json tools/backfill-historical-odds.ts --dry-run
 *   npx tsx --tsconfig tsconfig.server.json tools/backfill-historical-odds.ts --comp PD
 *   npx tsx --tsconfig tsconfig.server.json tools/backfill-historical-odds.ts --sync-ledger
 *
 * --comp SLUG: Restrict to a single competition (slug or numeric leagueId).
 *             Requires cache/predictions/historical-backtest-v3-{slug}-*.json to exist.
 * --sync-ledger: Seeds the OPS panel ledger with the most recent remaining value from
 *   the cache files. Run once after a backfill that predates ledger integration.
 *
 * The Odds API sport_key mapping for each league lives in COMP_CODE_TO_SPORT_KEY below.
 * To add a new league: add an entry here AND in server/prediction/historical-odds-store.ts.
 */

import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { config } from 'dotenv';
import { ApiUsageLedger } from '@sportpulse/canonical';

config();

// ── Config ──────────────────────────────────────────────────────────────────

const CACHE_DIR = path.resolve(process.cwd(), 'cache/historical-odds');
const BACKTEST_DIR = path.resolve(process.cwd(), 'cache/predictions');
const API_KEY = process.env.THE_ODDS_API_KEY ?? '';
const DELAY_MS = 1200; // ~50 req/min — well within paid plan limits
const MIN_YEAR = 2023;

// ── Competition code → sport_key ────────────────────────────────────────────

const COMP_CODE_TO_SPORT_KEY: Record<string, string> = {
  // Football-data codes
  PD:  'soccer_spain_la_liga',
  PL:  'soccer_epl',
  BL1: 'soccer_germany_bundesliga',
  SA:  'soccer_italy_serie_a',
  FL1: 'soccer_france_ligue_one',
  DED: 'soccer_netherlands_eredivisie',
  PPL: 'soccer_portugal_primeira_liga',
  // AF slugs
  URU: 'soccer_uruguay_primera_division',
  AR:  'soccer_argentina_primera_division',
  MX:  'soccer_mexico_ligamx',
  BR:  'soccer_brazil_campeonato',
  // AF numeric codes (comp:apifootball:N → code is the number)
  '140': 'soccer_spain_la_liga',
  '39':  'soccer_epl',
  '78':  'soccer_germany_bundesliga',
  '268': 'soccer_uruguay_primera_division',
  '128': 'soccer_argentina_primera_division',
  '262': 'soccer_mexico_ligamx',
  '71':  'soccer_brazil_campeonato',
  '265': 'soccer_chile_campeonato',
  // String codes
  'CL':  'soccer_chile_campeonato',
};

// ── Types ───────────────────────────────────────────────────────────────────

interface OddsOutcome {
  name: string;
  price: number;
}

interface OddsMarket {
  key: string;
  outcomes: OddsOutcome[];
}

interface OddsBookmaker {
  key: string;
  title: string;
  markets: OddsMarket[];
}

export interface OddsEvent {
  id: string;
  sport_key: string;
  commence_time: string;   // ISO-8601 UTC
  home_team: string;
  away_team: string;
  bookmakers: OddsBookmaker[];
}

interface HistoricalOddsResponse {
  timestamp: string;
  previous_timestamp: string | null;
  next_timestamp: string | null;
  data: OddsEvent[];
}

interface CacheFile {
  fetchedAt: string;
  snapshotDate: string;  // {YYYY-MM-DD}T00:00:00Z
  sportKey: string;
  events: OddsEvent[];
  remaining?: number;    // x-requests-remaining from API header
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function cacheFilePath(sportKey: string, date: string): string {
  // date = 'YYYY-MM-DD'
  return path.join(CACHE_DIR, sportKey, `${date}.json`);
}

function isCached(sportKey: string, date: string): boolean {
  return fs.existsSync(cacheFilePath(sportKey, date));
}

/**
 * Returns the nearest cached date for a sport_key within [date - maxDays, date].
 * Used to skip fetching when a recent cache file already covers this date's events
 * (The Odds API historical endpoint returns all upcoming events, typically 5–14 days ahead,
 * so one call per week is enough to cover an entire matchday).
 *
 * Returns the covering cache date string ('YYYY-MM-DD'), or null if none found.
 */
function findCoveringCache(sportKey: string, date: string, maxDays = 5): string | null {
  const dir = path.join(CACHE_DIR, sportKey);
  if (!fs.existsSync(dir)) return null;

  const dateMs = new Date(`${date}T00:00:00Z`).getTime();
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));

  for (let d = 0; d <= maxDays; d++) {
    const candidateMs = dateMs - d * 86400000;
    const candidateDate = new Date(candidateMs).toISOString().slice(0, 10);
    if (files.includes(`${candidateDate}.json`)) return candidateDate;
  }
  return null;
}

async function fetchHistoricalOdds(
  sportKey: string,
  date: string,  // 'YYYY-MM-DD'
): Promise<{ events: OddsEvent[]; remaining: number } | null> {
  const snapshotTs = `${date}T00:00:00Z`;
  const url = new URL(`https://api.the-odds-api.com/v4/historical/sports/${sportKey}/odds/`);
  url.searchParams.set('apiKey', API_KEY);
  url.searchParams.set('regions', 'eu,uk');
  url.searchParams.set('markets', 'h2h');
  url.searchParams.set('oddsFormat', 'decimal');
  url.searchParams.set('date', snapshotTs);

  const res = await fetch(url.toString());
  const remaining = parseInt(res.headers.get('x-requests-remaining') ?? '0', 10);

  if (res.status === 422) {
    // Date out of range for this sport_key (no historical data that far back)
    console.log(`  ⚠️  ${sportKey} ${date}: out of range (422) — skipping`);
    return { events: [], remaining };
  }
  if (res.status === 401) {
    throw new Error('THE_ODDS_API_KEY invalid or missing subscription');
  }
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  }

  const body = await res.json() as HistoricalOddsResponse;
  return { events: body.data ?? [], remaining };
}

function writeCacheFile(sportKey: string, date: string, events: OddsEvent[], remaining: number): void {
  const dir = path.join(CACHE_DIR, sportKey);
  fs.mkdirSync(dir, { recursive: true });

  const file: CacheFile = {
    fetchedAt: new Date().toISOString(),
    snapshotDate: `${date}T00:00:00Z`,
    sportKey,
    events,
    remaining,
  };

  const tmpPath = cacheFilePath(sportKey, date) + '.tmp';
  fs.writeFileSync(tmpPath, JSON.stringify(file, null, 2), 'utf-8');
  fs.renameSync(tmpPath, cacheFilePath(sportKey, date));
}

// ── Read backtest files ─────────────────────────────────────────────────────

function collectDatesByComp(): Map<string, Set<string>> {
  // Returns Map<competition_code, Set<'YYYY-MM-DD'>>
  const result = new Map<string, Set<string>>();

  if (!fs.existsSync(BACKTEST_DIR)) return result;

  const files = fs.readdirSync(BACKTEST_DIR).filter((f) => f.includes('backtest') && f.endsWith('.json'));

  for (const fname of files) {
    try {
      const raw = fs.readFileSync(path.join(BACKTEST_DIR, fname), 'utf-8');
      const data = JSON.parse(raw) as Record<string, unknown>;
      const snaps = (data['snapshots'] ?? data['records'] ?? []) as Record<string, unknown>[];

      for (const snap of snaps) {
        const kickoff = snap['kickoff_utc'] as string | undefined;
        const code = snap['competition_code'] as string | undefined;
        if (!kickoff || !code) continue;

        // Skip records before MIN_YEAR
        const year = parseInt(kickoff.slice(0, 4), 10);
        if (year < MIN_YEAR) continue;

        // Only process snapshots with actual prediction data (skip NOT_ELIGIBLE)
        const mode = snap['mode'] as string | undefined;
        if (mode === 'NOT_ELIGIBLE' || mode === 'ERROR') continue;

        if (!result.has(code)) result.set(code, new Set());
        result.get(code)!.add(kickoff.slice(0, 10)); // 'YYYY-MM-DD'
      }
    } catch (err) {
      console.warn(`  Warning: could not read ${fname}: ${err}`);
    }
  }

  return result;
}

// ── Ledger sync ──────────────────────────────────────────────────────────────

/**
 * Seeds the ledger with the most recent `remaining` value found across all
 * historical-odds cache files. This fixes the OPS panel counter when the
 * backfill was run before ledger integration was added.
 *
 * Usage: --sync-ledger
 */
function syncLedgerFromCache(ledger: ApiUsageLedger): void {
  console.log('=== Sync Ledger from Cache ===');

  if (!fs.existsSync(CACHE_DIR)) {
    console.log('No cache directory found. Nothing to sync.');
    return;
  }

  let latestRemaining: number | null = null;
  let latestFetchedAt: string | null = null;

  for (const sportKey of fs.readdirSync(CACHE_DIR)) {
    const dir = path.join(CACHE_DIR, sportKey);
    try {
      if (!fs.statSync(dir).isDirectory()) continue;
    } catch { continue; }

    for (const fname of fs.readdirSync(dir)) {
      if (!fname.endsWith('.json')) continue;
      try {
        const raw = fs.readFileSync(path.join(dir, fname), 'utf-8');
        const data = JSON.parse(raw) as CacheFile;
        if (data.remaining !== undefined && data.fetchedAt) {
          if (!latestFetchedAt || data.fetchedAt > latestFetchedAt) {
            latestFetchedAt = data.fetchedAt;
            latestRemaining = data.remaining;
          }
        }
      } catch { /* skip corrupt files */ }
    }
  }

  if (latestRemaining === null || latestFetchedAt === null) {
    console.log('No cache files with remaining field found. Nothing to sync.');
    return;
  }

  console.log(`Most recent API response: ${latestFetchedAt}, remaining: ${latestRemaining}`);

  const now = new Date().toISOString();
  const todayLocal = now.slice(0, 10);

  ledger.recordEvent({
    id: crypto.randomUUID(),
    providerKey: 'the-odds-api',
    usageDateLocal: todayLocal,
    unitType: 'REQUEST',
    usageUnits: 0,  // 0 — reconciliation seed, not a new call
    consumerType: 'BACKFILL_JOB',
    consumerId: 'sync-ledger',
    moduleKey: 'backfill-historical-odds',
    operationKey: 'sync-ledger',
    requestMethod: 'GET',
    endpointTemplate: '/v4/historical/sports/{sportKey}/odds/',
    statusCode: null,
    success: true,
    rateLimited: false,
    cacheHit: true,
    startedAtUtc: now,
    finishedAtUtc: now,
    latencyMs: 0,
    remoteLimit: 20000,
    remoteRemaining: latestRemaining,
    remoteResetAtUtc: null,
    errorCode: null,
    errorClass: null,
    requestId: null,
    metadataJson: JSON.stringify({ source: 'cache-scan', cachedAt: latestFetchedAt }),
    createdAtUtc: now,
  });

  const used = 20000 - latestRemaining;
  console.log(`✅ Ledger seeded: remaining=${latestRemaining} → ${used}/20000 used this month.`);
  console.log(`   Reload /admin/ops to see the updated counter.`);
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const syncLedger = args.includes('--sync-ledger');
  const compFilter = args.find((a) => a.startsWith('--comp='))?.slice(7)
    ?? (args.indexOf('--comp') !== -1 ? args[args.indexOf('--comp') + 1] : null);

  const ledger = new ApiUsageLedger(path.join(process.cwd(), 'cache', 'api-usage.db'));

  if (syncLedger) {
    syncLedgerFromCache(ledger);
    return;
  }

  if (!API_KEY && !dryRun) {
    console.error('ERROR: THE_ODDS_API_KEY not set in environment');
    process.exit(1);
  }

  console.log('=== Historical Odds Backfill ===');
  console.log(`Cache dir: ${CACHE_DIR}`);
  if (dryRun) console.log('DRY RUN — no API calls will be made');
  if (compFilter) console.log(`Filter: only comp code "${compFilter}"`);

  // Collect all (comp_code, date) pairs from backtest files
  const datesByComp = collectDatesByComp();

  // Build work list: (sport_key, date) pairs to fetch
  // Optimization: skip dates covered by a cache file from the previous 5 days.
  // The historical endpoint returns all upcoming events (~5–14 days ahead), so
  // one call covers an entire matchday — no need to call on every match date.
  const workItems: Array<{ sportKey: string; date: string; compCode: string }> = [];

  for (const [compCode, dates] of datesByComp) {
    if (compFilter && compCode !== compFilter) continue;

    const sportKey = COMP_CODE_TO_SPORT_KEY[compCode];
    if (!sportKey) {
      console.log(`  ⚠️  No sport_key for comp code "${compCode}" — skipping`);
      continue;
    }

    for (const date of [...dates].sort()) {
      // Skip if already cached exactly OR covered by a recent cache file
      if (!isCached(sportKey, date) && findCoveringCache(sportKey, date) === null) {
        workItems.push({ sportKey, date, compCode });
      }
    }
  }

  // Deduplicate: multiple comp codes might share the same sport_key + date.
  // Also apply rolling window: once we decide to fetch a date, mark the next
  // 5 days as covered so consecutive dates in the work list collapse.
  const seen = new Set<string>();
  const uniqueWork: Array<{ sportKey: string; date: string; compCode: string }> = [];
  const lastFetchedMs = new Map<string, number>(); // sportKey → ms of last queued fetch

  for (const item of workItems) {
    const { sportKey, date } = item;
    const dateMs = new Date(`${date}T00:00:00Z`).getTime();
    const lastMs = lastFetchedMs.get(sportKey) ?? 0;

    // Skip if within 5 days of the last queued fetch for this sport_key
    if (dateMs - lastMs < 5 * 86400000) continue;

    const key = `${sportKey}:${date}`;
    if (seen.has(key)) continue;
    seen.add(key);
    lastFetchedMs.set(sportKey, dateMs);
    uniqueWork.push(item);
  }

  // Stats
  let covered = 0;
  let exactCached = 0;
  for (const [compCode, dates] of datesByComp) {
    if (compFilter && compCode !== compFilter) continue;
    const sportKey = COMP_CODE_TO_SPORT_KEY[compCode];
    if (!sportKey) continue;
    for (const date of dates) {
      if (isCached(sportKey, date)) { exactCached++; covered++; }
      else if (findCoveringCache(sportKey, date) !== null) covered++;
    }
  }

  console.log(`\nWork summary:`);
  console.log(`  Exact cached:   ${exactCached} date-sport_key pairs`);
  console.log(`  Window covered: ${covered - exactCached} date-sport_key pairs (within 5-day window of existing cache)`);
  console.log(`  To fetch:       ${uniqueWork.length} date-sport_key pairs (1 call per ~5-day matchday window)`);

  if (uniqueWork.length === 0) {
    console.log('\n✅ All dates already cached — nothing to do.');
    return;
  }

  // Group by sport_key for display
  const bySportKey = new Map<string, number>();
  for (const { sportKey } of uniqueWork) {
    bySportKey.set(sportKey, (bySportKey.get(sportKey) ?? 0) + 1);
  }
  console.log('\nBreakdown by sport_key:');
  for (const [sk, count] of [...bySportKey.entries()].sort()) {
    console.log(`  ${sk}: ${count} dates`);
  }

  if (dryRun) {
    console.log('\nDRY RUN complete — no API calls made.');
    console.log('Sample dates to fetch:');
    uniqueWork.slice(0, 5).forEach(({ sportKey, date }) =>
      console.log(`  ${sportKey} ${date}`)
    );
    return;
  }

  // Fetch loop
  console.log(`\nStarting fetch (${DELAY_MS}ms delay between calls)...\n`);
  let fetched = 0;
  let errors = 0;
  let totalEvents = 0;

  for (const { sportKey, date, compCode } of uniqueWork) {
    const idx = fetched + errors + 1;
    process.stdout.write(`[${idx}/${uniqueWork.length}] ${sportKey} ${date} ... `);

    try {
      const result = await fetchHistoricalOdds(sportKey, date);
      if (result) {
        writeCacheFile(sportKey, date, result.events, result.remaining);
        console.log(`✓ ${result.events.length} events (remaining: ${result.remaining})`);
        totalEvents += result.events.length;
        fetched++;

        // Record to ledger so the OPS panel shows accurate monthly consumption.
        const now = new Date().toISOString();
        ledger.recordEvent({
          id: crypto.randomUUID(),
          providerKey: 'the-odds-api',
          usageDateLocal: date,
          unitType: 'REQUEST',
          usageUnits: 1,
          consumerType: 'BACKFILL_JOB',
          consumerId: `backfill:${compCode}`,
          moduleKey: 'backfill-historical-odds',
          operationKey: 'historical-sports-odds',
          requestMethod: 'GET',
          endpointTemplate: '/v4/historical/sports/{sportKey}/odds/',
          statusCode: 200,
          success: true,
          rateLimited: false,
          cacheHit: false,
          startedAtUtc: now,
          finishedAtUtc: now,
          latencyMs: 0,
          remoteLimit: 20000,
          remoteRemaining: result.remaining,
          remoteResetAtUtc: null,
          errorCode: null,
          errorClass: null,
          requestId: null,
          metadataJson: JSON.stringify({ sportKey, events: result.events.length }),
          createdAtUtc: now,
        });

        if (result.remaining < 10) {
          console.warn(`\n⚠️  WARNING: Only ${result.remaining} API requests remaining!`);
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.log(`✗ ERROR: ${msg}`);
      errors++;
    }

    // Delay between calls (skip after last item)
    if (fetched + errors < uniqueWork.length) {
      await sleep(DELAY_MS);
    }
  }

  console.log(`\n=== Backfill complete ===`);
  console.log(`  Fetched:      ${fetched} date-sport_key pairs`);
  console.log(`  Total events: ${totalEvents}`);
  console.log(`  Errors:       ${errors}`);
  console.log(`\nNext step: run tools/analyze-blend-accuracy.ts to compute blended accuracy.`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
